// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoZSamIU8J7rSVuD5YnB2dQWVhw1x_Tco',
    appId: '1:452898752963:web:a286e5f180a568618e1576',
    messagingSenderId: '452898752963',
    projectId: 'chatapptute-f3cbe',
    authDomain: 'chatapptute-f3cbe.firebaseapp.com',
    storageBucket: 'chatapptute-f3cbe.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAobjaha75CnApOJ7nF4fLNn0ntzNbtHMo',
    appId: '1:452898752963:android:56e6ad2bf19bec248e1576',
    messagingSenderId: '452898752963',
    projectId: 'chatapptute-f3cbe',
    storageBucket: 'chatapptute-f3cbe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRua-8uWR02sSDGb57DNIiIQXlrGdCKTo',
    appId: '1:452898752963:ios:bd54a99763a580f48e1576',
    messagingSenderId: '452898752963',
    projectId: 'chatapptute-f3cbe',
    storageBucket: 'chatapptute-f3cbe.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRua-8uWR02sSDGb57DNIiIQXlrGdCKTo',
    appId: '1:452898752963:ios:bd54a99763a580f48e1576',
    messagingSenderId: '452898752963',
    projectId: 'chatapptute-f3cbe',
    storageBucket: 'chatapptute-f3cbe.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoZSamIU8J7rSVuD5YnB2dQWVhw1x_Tco',
    appId: '1:452898752963:web:4dcc13e96df073a18e1576',
    messagingSenderId: '452898752963',
    projectId: 'chatapptute-f3cbe',
    authDomain: 'chatapptute-f3cbe.firebaseapp.com',
    storageBucket: 'chatapptute-f3cbe.appspot.com',
  );
}
